// Code generated by genny - Generics for Go; DO NOT EDIT.
// More information at github.com/cheekybits/genny
// or with 'go doc github.com/cheekybits/genny'

package unexported

import "fmt"

func myTypeInspect(s *myType) string {
	return fmt.Sprintf("%#v", s)
}
