// Code generated by genny - Generics for Go; DO NOT EDIT.
// More information at github.com/cheekybits/genny
// or with 'go doc github.com/cheekybits/genny'

package changed

// IntQueue is a queue of Ints.
type IntQueue struct {
	items []int
}

func NewIntQueue() *IntQueue {
	return &IntQueue{items: make([]int, 0)}
}
func (q *IntQueue) Push(item int) {
	q.items = append(q.items, item)
}
func (q *IntQueue) Pop() int {
	item := q.items[0]
	q.items = q.items[1:]
	return item
}
