// Code generated by genny - Generics for Go; DO NOT EDIT.
// More information at github.com/cheekybits/genny
// or with 'go doc github.com/cheekybits/genny'

package multipletypes

type InterfaceIntMap map[interface{}]int

func (m InterfaceIntMap) Has(key interface{}) bool {
	_, ok := m[key]
	return ok
}

func (m InterfaceIntMap) Get(key interface{}) int {
	return m[key]
}

func (m InterfaceIntMap) Set(key interface{}, value int) InterfaceIntMap {
	m[key] = value
	return m
}
