// Code generated by genny - Generics for Go; DO NOT EDIT.
// More information at github.com/cheekybits/genny
// or with 'go doc github.com/cheekybits/genny'

package multipletypes

type StringIntMap map[string]int

func (m StringIntMap) Has(key string) bool {
	_, ok := m[key]
	return ok
}

func (m StringIntMap) Get(key string) int {
	return m[key]
}

func (m StringIntMap) Set(key string, value int) StringIntMap {
	m[key] = value
	return m
}
