// Code generated by genny - Generics for Go; DO NOT EDIT.
// More information at github.com/cheekybits/genny
// or local at $GOPATH/src/github.com/cheekybits/genny

package gogenerate

type StringStringMap map[string]string

func NewStringStringMap() map[string]string {
	return make(map[string]string)
}

type StringIntMap map[string]int

func NewStringIntMap() map[string]int {
	return make(map[string]int)
}

type IntStringMap map[int]string

func NewIntStringMap() map[int]string {
	return make(map[int]string)
}

type IntIntMap map[int]int

func NewIntIntMap() map[int]int {
	return make(map[int]int)
}
