// Code generated by genny - Generics for Go; DO NOT EDIT.
// More information at github.com/cheekybits/genny
// or with 'go doc github.com/cheekybits/genny'

package numbers

func IntMax(a, b int) int {
	if a > b {
		return a
	}
	return b
}
